### ISSUE TITLE
Is there any way to make a window transparent

### ISSUE THREAD

**Issue by aojianwu** [MicrosoftDocs/webview2-win32-reference#11]
I have set the native window to transparent, but the background color of the window is still white.

**Comment by johna-ms** [comment]
Hi, there's a feature in the new prerelease package called DefaultBackgroundColor which is probably what you're looking for. You can set the WebView default background color to be transparent and it will render any web content over contents of the parent window. The feature is coming out this Monday 1/25 in version 773. Hope this helps!

**Comment by peiche-jessica** [comment]
This should now be available in WebView2 SDK [1.0.781-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.781-prerelease). If this is still an issue please let us know in [WebView2Feedback](https://github.com/MicrosoftEdge/WebView2Feedback). Thanks!
- https://docs.microsoft.com/microsoft-edge/webview2/reference/win32/icorewebview2controller2?view=webview2-1.0.781-prerelease#get_defaultbackgroundcolor
